block_x_dim = 50
block_y_dim = 16
x_offset = 3
y_offset = 5

hosts = [ "localhost", "justin", "boyi", "adam", "spydur", "michael", "kevin" ]

keepers = [ "fb_memory_usage.total",
            "fb_memory_usage.reserved",
            "fb_memory_usage.free",
            "fb_memory_usage.used",
            "gpu_module_id",
            "gpu_power_readings.power_draw",
            "product_name",
            "fan_speed",
            "module_power_readings.power_draw",
            "module_power_readings.default_power_limit",
            "temperature.gpu_temp",
            "temperature.gpu_target_temperature" ]

outfile = "gpuview.out"

toolname = "nvidia-smi -q --xml-format"

