# Size of the display block for a host.
block_x_dim = 50
block_y_dim = 16

# In case we do not want to start the display in the top left
# corner of the screen. We can give it a little margin here.
x_offset = 3
y_offset = 5

# Computers we want to talk to.
hosts = [ "kevin", "adam", "alexis", "boyi", "camryn", "cooper", "erica", "evan", "irene2", "justin", "mayer", "michael", "sarah", "thais" ]
# hosts = [ "localhost", "justin", "boyi", "adam", "spydur", "michael", "kevin" ]

# Data we care about.
keepers = [ "fb_memory_usage.total",
            "fb_memory_usage.reserved",
            "fb_memory_usage.free",
            "fb_memory_usage.used",
            "gpu_module_id",
            "gpu_power_readings.power_draw",
            "product_name",
            "fan_speed",
            "module_power_readings.power_draw",
            "module_power_readings.default_power_limit",
            "temperature.gpu_temp",
            "temperature.gpu_target_temperature" ]

# Temp file where the child processes syncronize the data they
# collect from hosts.
outfile = "gpuview.out"

# Above this value, we show RED.
red_line = 0.85

# In seconds.
timeout = 5

# How we get the data.
toolnames.gpu = "nvidia-smi -q --xml-format"
toolnames.cpu = "cat /proc/loadavg"
toolnames.static.cpu = "grep -c ^processor /proc/cpuinfo"
toolnames.static.mem = "grep MemTotal /proc/meminfo"

# Above this line, we show YELLOW.
yellow_line = 0.7
