block_x_dim = 40
block_y_dim = 16

hosts = [ "localhost" ]

keepers = [ "fb_memory_usage.total",
            "fb_memory_usage.used",
            "gpu_module_id",
            "gpu_power_readings.power_draw",
            "product_name",
            "temperature.gpu_temp" ]

outfile = "gpuview.out"

toolname = "nvidia-smi -q --xml-format"

